# Generated by Django 5.2.16 on 2026-07-30 10:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("CLINICAL_NOTE", "Clinical note"),
                            ("PATIENT_HISTORY", "Patient history"),
                            ("RECEPTION_INTAKE", "Reception intake"),
                        ],
                        max_length=30,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("schema", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["target", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target", "version"),
                        name="formdef_unique_target_version",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("target",),
                        name="formdef_one_active_per_target",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClinicalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complaints",
                    models.TextField(
                        blank=True, help_text="What the patient reports today."
                    ),
                ),
                (
                    "examination",
                    models.TextField(blank=True, help_text="Findings on examination."),
                ),
                (
                    "assessment",
                    models.TextField(blank=True, help_text="Clinical impression."),
                ),
                (
                    "plan",
                    models.TextField(
                        blank=True, help_text="Management plan and advice."
                    ),
                ),
                (
                    "systolic_bp",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "diastolic_bp",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("pulse", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "form_version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Which version of the note form produced `extra`. Lets old notes keep rendering correctly after the form changes.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="patients.patient",
                    ),
                ),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note",
                        to="appointments.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-created_at"],
                        name="clinical_cl_patient_32ae11_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                ("icd10_code", models.CharField(blank=True, max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RESOLVED", "Resolved"),
                            ("RULED_OUT", "Ruled out"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "diagnosed_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("resolved_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="patients.patient",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Visit at which this was first recorded.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnoses",
                        to="appointments.visit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "diagnoses",
                "ordering": ["-diagnosed_on"],
                "indexes": [
                    models.Index(
                        fields=["patient", "status"],
                        name="clinical_di_patient_d0673c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Investigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(db_index=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("THYROID", "Thyroid"),
                            ("DIABETES", "Diabetes / Glycaemic"),
                            ("HORMONE", "Hormone assay"),
                            ("BONE", "Bone & mineral"),
                            ("LIPID", "Lipid profile"),
                            ("IMAGING", "Imaging"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                (
                    "value_numeric",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Numeric copy of the value, when it is a number. Used for trends.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("reference_range", models.CharField(blank=True, max_length=100)),
                ("is_abnormal", models.BooleanField(default=False)),
                (
                    "performed_on",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("lab_name", models.CharField(blank=True, max_length=200)),
                (
                    "report_file",
                    models.FileField(blank=True, null=True, upload_to="reports/%Y/%m/"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investigations",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_investigations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        help_text="The visit this result was reviewed at, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investigations",
                        to="appointments.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_on", "test_name"],
                "indexes": [
                    models.Index(
                        fields=["patient", "test_name", "-performed_on"],
                        name="clinical_in_patient_c112eb_idx",
                    )
                ],
            },
        ),
    ]
