# Generated by Django 5.2.16 on 2026-08-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0002_referenceletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalnote",
            name="clinical_notes",
            field=models.TextField(
                blank=True, help_text="The doctor's own reference. Never printed."
            ),
        ),
        migrations.AddField(
            model_name="clinicalnote",
            name="prescription_note",
            field=models.TextField(
                blank=True,
                help_text="Printed on the prescription written for this visit.",
            ),
        ),
    ]
