# Generated by Django 5.2.16 on 2026-08-11 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0010_remove_doctorleave"),
        ("clinical", "0003_clinicalnote_clinical_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="referenceletter",
            name="visit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reference_letters",
                to="appointments.visit",
            ),
        ),
    ]
