# Generated by Django 5.2.16 on 2026-08-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0004_referenceletter_visit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ICD10Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10, unique=True)),
                ("description", models.CharField(db_index=True, max_length=300)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
    ]
