# Generated by Django 5.2.16 on 2026-08-13 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0006_load_icd10_codes"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="investigation",
            name="lab_test",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when the test name was picked from the master list.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investigations",
                to="clinical.labtest",
            ),
        ),
        migrations.CreateModel(
            name="LabReferenceRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("ANY", "Any"),
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "age_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "age_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("age_unit", models.CharField(default="years", max_length=10)),
                ("pregnancy_status", models.CharField(blank=True, max_length=50)),
                ("fasting_status", models.CharField(blank=True, max_length=50)),
                (
                    "low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("unit", models.CharField(max_length=50)),
                ("source", models.CharField(max_length=300)),
                (
                    "source_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MASTER_ONLY_REFERENCE_REQUIRED", "Reference required"),
                            ("REVIEW_REQUIRED", "Review required"),
                            ("VALIDATED", "Validated"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        default="MASTER_ONLY_REFERENCE_REQUIRED",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lab_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_ranges",
                        to="clinical.labtest",
                    ),
                ),
            ],
            options={
                "ordering": ["lab_test__name", "sex", "age_min"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("low__isnull", False),
                            ("high__isnull", False),
                            _connector="OR",
                        ),
                        name="reference_range_needs_a_bound",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LabUnitConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_unit", models.CharField(max_length=50)),
                ("to_unit", models.CharField(max_length=50)),
                ("multiplier", models.DecimalField(decimal_places=8, max_digits=18)),
                (
                    "offset",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "lab_test",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank only for a conversion that holds for every test.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_conversions",
                        to="clinical.labtest",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["from_unit", "to_unit"],
                        name="clinical_la_from_un_1ee610_idx",
                    )
                ],
            },
        ),
    ]
