# Generated by Django 5.2.16 on 2026-08-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0008_load_lab_tests"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="icd10code",
            options={
                "ordering": ["code"],
                "verbose_name": "ICD-10 code",
                "verbose_name_plural": "ICD-10 codes",
            },
        ),
    ]
