# Generated by Django 5.2.16 on 2026-08-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0009_alter_icd10code_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investigation",
            name="category",
            field=models.CharField(
                choices=[
                    ("CLINICAL_CHEMISTRY", "Clinical Chemistry"),
                    ("ENDOCRINOLOGY", "Endocrinology"),
                    ("HEMATOLOGY", "Hematology"),
                    ("CARDIAC_MUSCLE", "Cardiac and Muscle"),
                    ("COAGULATION", "Coagulation"),
                    ("INFECTIOUS_SEROLOGY", "Infectious Disease and Serology"),
                    ("INFLAMMATION_IMMUNOLOGY", "Inflammation and Immunology"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=32,
            ),
        ),
    ]
