# Generated by Django 5.2.16 on 2026-08-05 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CallbackRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=20)),
                ("preferred_doctor", models.CharField(blank=True, max_length=120)),
                ("concern", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "To call"),
                            ("DONE", "Called back"),
                            ("IGNORED", "No action needed"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="callbacks_handled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "callback request",
                "ordering": ["-created_at"],
            },
        ),
    ]
