"""
KAN-21 — adding a doctor, and the invitation that lets them set a password.

The security note on the ticket is the point of the story, so most of these are
about what must *not* happen: no password generated by reception, none shown on
a screen, none in an email, none in a log, and a token that works once, expires,
and is stored hashed.
"""

from datetime import timedelta

from django.conf import settings
from django.core import mail
from django.test import TestCase, override_settings
from django.urls import reverse
from django.utils import timezone

from accounts import invitations
from accounts.models import (
    DoctorInvitation, DoctorProfile, Role, Specialisation, User,
)
from appointments.models import Cabin, DoctorSchedule

from .factories import make_doctor, make_receptionist

def _form(**overrides):
    """
    A filled-in Add Doctor form.

    The specialisation is looked up rather than hard-coded: KAN-37 turned it
    from a fixed choice into a row in a table, so its value is a primary key
    that differs between runs.
    """
    payload = {
        "full_name": "Vrushali Kulkarni",
        "email": "vrushali@example.in",
        "phone": "9820012345",
        "specialisation": str(
            Specialisation.objects.get(name="Paediatric Endocrinology").pk
        ),
        "new_specialisation": "",
        "registration_number": "MMC-12345",
        "qualification": "MBBS, MD, DM",
    }
    payload.update(overrides)
    return payload


class TestAddingADoctor(TestCase):
    """FR-1, FR-2, FR-8, AC-1 and AC-7."""

    def setUp(self):
        self.receptionist = make_receptionist()
        self.client.force_login(self.receptionist)

    def _add(self, **overrides):
        return self.client.post(reverse("reception_add_doctor"), _form(**overrides))

    def test_the_record_is_created(self):
        self._add()
        doctor = User.objects.get(email="vrushali@example.in")
        self.assertEqual(doctor.role, Role.DOCTOR)
        self.assertEqual(doctor.display_name, "Vrushali Kulkarni")

    def test_the_specialisation_is_stored(self):
        # FR-9, as revised by KAN-37 — what the calendar filter reads.
        self._add()
        profile = DoctorProfile.objects.get(user__email="vrushali@example.in")
        self.assertEqual(profile.specialisation.name, "Paediatric Endocrinology")

    def test_the_account_starts_pending(self):
        self._add()
        profile = DoctorProfile.objects.get(user__email="vrushali@example.in")
        self.assertTrue(profile.is_pending)
        self.assertEqual(profile.status_label, "Pending")

    def test_a_pending_doctor_cannot_sign_in(self):
        self._add()
        doctor = User.objects.get(email="vrushali@example.in")
        self.assertFalse(doctor.is_active)
        self.assertFalse(doctor.has_usable_password())

    def test_an_invitation_email_is_sent(self):
        self._add()
        self.assertEqual(len(mail.outbox), 1)
        self.assertEqual(mail.outbox[0].to, ["vrushali@example.in"])

    def test_a_duplicate_email_is_refused(self):
        # FR-8 / AC-7.
        self._add()
        response = self._add(full_name="Somebody Else")
        self.assertEqual(User.objects.filter(email="vrushali@example.in").count(), 1)
        self.assertContains(response, "already registered with that email")

    def test_the_form_has_no_password_field(self):
        # FR-10. There is no box for one, and there is not meant to be.
        body = self.client.get(reverse("reception_add_doctor")).content.decode()
        self.assertNotIn('type="password"', body)

    def test_the_screen_says_who_sets_the_password(self):
        body = self.client.get(reverse("reception_add_doctor")).content.decode()
        self.assertIn("You do not set their password", body)

    def test_a_doctor_cannot_add_doctors(self):
        self.client.force_login(make_doctor())
        self.assertEqual(self._add().status_code, 403)


class TestTheEmailCarriesNoCredential(TestCase):
    """AC-9 and T-7 — the check the ticket asks for by name."""

    def setUp(self):
        self.client.force_login(make_receptionist())
        self.client.post(reverse("reception_add_doctor"), _form())
        self.message = mail.outbox[0]

    def test_it_contains_a_link(self):
        self.assertIn("/activate/", self.message.body)

    def test_it_says_no_password_is_in_it(self):
        self.assertIn("does not contain a password", self.message.body)

    def test_it_tells_them_their_username(self):
        # Otherwise there is nowhere the doctor ever learns what to type at
        # the login screen — this email is it.
        doctor = User.objects.get(email="vrushali@example.in")
        self.assertIn(doctor.username, self.message.body)

    def test_it_carries_nothing_that_looks_like_a_password_field(self):
        lowered = self.message.body.lower()
        for word in ("your password is", "temporary password", "password:"):
            self.assertNotIn(word, lowered, msg=word)

    def test_the_raw_token_is_not_stored_anywhere(self):
        # The whole reason it is hashed: a leaked backup yields nothing usable.
        raw = self.message.body.split("/activate/")[1].split("/")[0]
        invitation = DoctorInvitation.objects.get()
        self.assertNotEqual(invitation.token_hash, raw)
        self.assertEqual(invitation.token_hash, DoctorInvitation.hash_token(raw))

    def test_the_stored_hash_cannot_be_used_as_the_token(self):
        invitation = DoctorInvitation.objects.get()
        response = self.client.get(
            reverse("doctor_activate", args=[invitation.token_hash])
        )
        self.assertEqual(response.status_code, 400)


def _token_from_email(index=0):
    return mail.outbox[index].body.split("/activate/")[1].split("/")[0].strip()


class TestActivating(TestCase):
    """FR-3, FR-4, AC-2, AC-5 and AC-6."""

    def setUp(self):
        self.client.force_login(make_receptionist())
        self.client.post(reverse("reception_add_doctor"), _form())
        self.doctor = User.objects.get(email="vrushali@example.in")
        self.token = _token_from_email()
        self.client.logout()

    def _activate(self, token=None, password="a-really-good-passphrase"):
        return self.client.post(
            reverse("doctor_activate", args=[token or self.token]),
            {"new_password1": password, "new_password2": password},
        )

    def test_the_link_opens_without_signing_in(self):
        response = self.client.get(reverse("doctor_activate", args=[self.token]))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Choose your password")

    def test_setting_a_password_activates_the_account(self):
        self._activate()
        self.doctor.refresh_from_db()
        self.assertTrue(self.doctor.is_active)
        self.assertTrue(self.doctor.has_usable_password())
        self.assertFalse(self.doctor.doctor_profile.is_pending)

    def test_the_doctor_can_then_sign_in(self):
        self._activate(password="a-really-good-passphrase")
        self.client.logout()
        self.assertTrue(self.client.login(
            username=self.doctor.username, password="a-really-good-passphrase",
        ))

    def test_the_link_only_works_once(self):
        # AC-5.
        self._activate()
        self.client.logout()
        response = self.client.get(reverse("doctor_activate", args=[self.token]))
        self.assertEqual(response.status_code, 400)
        self.assertContains(response, "already been used", status_code=400)

    def test_an_expired_link_is_refused(self):
        # AC-6.
        invitation = DoctorInvitation.objects.get()
        invitation.expires_at = timezone.now() - timedelta(seconds=1)
        invitation.save(update_fields=["expires_at"])

        response = self.client.get(reverse("doctor_activate", args=[self.token]))
        self.assertContains(response, "expired", status_code=400)

    def test_an_expired_link_cannot_be_posted_at_either(self):
        invitation = DoctorInvitation.objects.get()
        invitation.expires_at = timezone.now() - timedelta(seconds=1)
        invitation.save(update_fields=["expires_at"])

        self._activate()
        self.doctor.refresh_from_db()
        self.assertFalse(self.doctor.is_active)

    def test_an_invented_token_is_refused(self):
        response = self.client.get(reverse("doctor_activate", args=["not-a-real-token"]))
        self.assertEqual(response.status_code, 400)

    # The test settings switch the password validators off for speed, so these
    # two turn them back on — otherwise they would assert that a policy applies
    # while running with no policy at all, and pass for the wrong reason.
    POLICY = [
        {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
         "OPTIONS": {"min_length": 10}},
        {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    ]

    @override_settings(AUTH_PASSWORD_VALIDATORS=POLICY)
    def test_a_password_that_fails_policy_is_refused(self):
        response = self._activate(password="abc")
        self.doctor.refresh_from_db()
        self.assertFalse(self.doctor.is_active)
        self.assertContains(response, "too short")

    @override_settings(AUTH_PASSWORD_VALIDATORS=POLICY)
    def test_the_invitation_survives_a_refused_password(self):
        # Otherwise one weak attempt burns the only link they have.
        self._activate(password="abc")
        self.assertTrue(DoctorInvitation.objects.get().is_usable)


class TestResending(TestCase):
    """FR-6, AC-8 and T-8."""

    def setUp(self):
        self.receptionist = make_receptionist()
        self.client.force_login(self.receptionist)
        self.client.post(reverse("reception_add_doctor"), _form())
        self.doctor = User.objects.get(email="vrushali@example.in")
        self.first_token = _token_from_email()

    def _resend(self):
        return self.client.post(
            reverse("reception_resend_invitation", args=[self.doctor.pk])
        )

    def test_a_second_email_is_sent(self):
        self._resend()
        self.assertEqual(len(mail.outbox), 2)

    def test_the_new_link_works(self):
        self._resend()
        self.client.logout()
        response = self.client.get(
            reverse("doctor_activate", args=[_token_from_email(1)])
        )
        self.assertEqual(response.status_code, 200)

    def test_the_original_link_stops_working(self):
        # AC-8 / T-8. This is what makes a mistyped address safe to correct.
        self._resend()
        self.client.logout()
        response = self.client.get(
            reverse("doctor_activate", args=[self.first_token])
        )
        self.assertContains(response, "no longer valid", status_code=400)

    def test_resending_to_an_activated_doctor_sends_a_password_reset(self):
        # Superseded: this used to be a no-op. It now doubles as "forgotten
        # password" for a doctor who has already set one — see
        # test_doctor_password_reset.py for the full behaviour.
        self.client.logout()
        self.client.post(
            reverse("doctor_activate", args=[self.first_token]),
            {"new_password1": "a-really-good-passphrase",
             "new_password2": "a-really-good-passphrase"},
        )
        mail.outbox.clear()

        self.client.force_login(self.receptionist)
        self._resend()
        self.assertEqual(len(mail.outbox), 1)
        self.assertIn("Reset your password", mail.outbox[0].subject)

    def test_a_doctor_cannot_resend_invitations(self):
        self.client.force_login(make_doctor())
        self.assertEqual(self._resend().status_code, 403)


class TestPendingDoctorsAreNotSchedulable(TestCase):
    """FR-7, AC-3, AC-4 and T-3."""

    def setUp(self):
        self.receptionist = make_receptionist()
        self.client.force_login(self.receptionist)
        self.client.post(reverse("reception_add_doctor"), _form())
        self.pending = User.objects.get(email="vrushali@example.in")
        self.cabin = Cabin.objects.create(name="Cabin 1")
        self.monday = timezone.localdate()
        while self.monday.weekday() != 0:
            self.monday += timedelta(days=1)

    def _give_hours(self, doctor):
        # KAN-50 removed the availability screen; the calendar's add-event
        # pop-up is the one way in now, and the rule has to hold there.
        return self.client.post(
            reverse("reception_add_calendar_event"),
            {"event_type": "hours", "doctor": doctor.pk, "cabin": self.cabin.pk,
             "date": self.monday.isoformat(), "repeat": "weekly",
             "start_time": "10:00", "end_time": "13:00"},
            follow=True,
        )

    def test_a_pending_doctor_is_refused_working_hours(self):
        # AC-3 — refused.
        self._give_hours(self.pending)
        self.assertEqual(DoctorSchedule.objects.filter(doctor=self.pending).count(), 0)

    def test_the_calendar_says_why_they_are_missing(self):
        # The other half of AC-3. They are absent from every dropdown on the
        # screen that gives out hours, and a name that is simply missing reads
        # as a fault in the system rather than as a step nobody has finished.
        response = self.client.get(reverse("reception_calendar"))
        self.assertContains(response, "Cannot be given hours yet")
        self.assertContains(response, "Vrushali Kulkarni")

    def test_a_doctor_is_not_told_whose_invitation_is_outstanding(self):
        # Reception's business, not one doctor's business about another.
        active = make_doctor(username="dr-active", email="active@example.in")
        DoctorProfile.objects.create(user=active, activated_at=timezone.now())
        self.client.force_login(active)

        response = self.client.get(reverse("reception_calendar"))
        self.assertNotContains(response, "Cannot be given hours yet")
        # Checked against the context rather than the page: the test client
        # keeps one cookie jar across force_login, so the receptionist's
        # success toast from setUp is still queued and carries the name. A
        # browser gets a fresh session per sign-in and never sees it.
        self.assertEqual(list(response.context["pending_doctors"]), [])

    def test_the_guard_holds_for_a_doctor_who_is_active_but_never_activated(self):
        # The case the dropdown filter does not catch: an account made before
        # invitations existed, or one enabled by hand in the admin.
        stray = make_doctor(username="dr-stray", email="stray@example.in")
        DoctorProfile.objects.create(user=stray)          # activated_at is None

        response = self._give_hours(stray)
        self.assertEqual(DoctorSchedule.objects.filter(doctor=stray).count(), 0)
        self.assertContains(response, "has not set their password yet")

    def test_an_active_doctor_is_given_them(self):
        # AC-4.
        active = make_doctor(username="dr-active", email="active@example.in")
        DoctorProfile.objects.create(user=active, activated_at=timezone.now())

        self._give_hours(active)
        self.assertEqual(DoctorSchedule.objects.filter(doctor=active).count(), 1)

    def test_a_pending_doctor_is_not_offered_for_booking(self):
        # Checked against the doctor dropdown rather than the whole page: the
        # success toast from adding them is still on screen and carries the name.
        response = self.client.get(reverse("reception_new_booking"))
        choices = response.context["form"].fields["doctor"].queryset
        self.assertNotIn(self.pending, choices)

    def test_the_doctor_list_shows_them_as_pending(self):
        # FR-5 — reception has to be able to see why they are missing.
        response = self.client.get(reverse("reception_doctors"))
        self.assertContains(response, "Vrushali Kulkarni")
        self.assertContains(response, "Pending")

    def test_the_list_offers_a_resend_for_them(self):
        self.assertContains(
            self.client.get(reverse("reception_doctors")),
            reverse("reception_resend_invitation", args=[self.pending.pk]),
        )


class TestTheInvitationModel(TestCase):
    """The rules the views depend on, checked without going through a screen."""

    def setUp(self):
        self.doctor = make_doctor(username="dr-x", email="x@example.in")

    def test_issuing_returns_a_token_that_is_not_stored(self):
        invitation, raw = DoctorInvitation.issue(self.doctor)
        self.assertNotIn(raw, (invitation.token_hash,))
        self.assertEqual(len(invitation.token_hash), 64)

    def test_a_token_is_long_enough_not_to_be_guessed(self):
        _, raw = DoctorInvitation.issue(self.doctor)
        self.assertGreaterEqual(len(raw), 32)

    def test_two_issues_never_collide(self):
        tokens = {DoctorInvitation.issue(self.doctor)[1] for _ in range(20)}
        self.assertEqual(len(tokens), 20)

    def test_issuing_revokes_what_came_before(self):
        first, _ = DoctorInvitation.issue(self.doctor)
        DoctorInvitation.issue(self.doctor)

        first.refresh_from_db()
        self.assertIsNotNone(first.revoked_at)
        self.assertFalse(first.is_usable)

    def test_the_default_window_comes_from_the_clinic_settings(self):
        invitation, _ = DoctorInvitation.issue(self.doctor)
        expected = timezone.now() + timedelta(days=settings.CLINIC.INVITATION_DAYS)
        self.assertLess(abs((invitation.expires_at - expected).total_seconds()), 60)

    def test_a_consumed_invitation_is_not_usable(self):
        invitation, _ = DoctorInvitation.issue(self.doctor)
        invitation.consume()
        self.assertFalse(invitation.is_usable)
        self.assertEqual(invitation.state, "used")


class TestTheEmailReadsAsPlainText(TestCase):
    """
    Django escapes template variables for HTML whether or not the template is
    HTML, so the clinic's name arrived as "Centre for Endocrine &amp; Metabolic
    Health" in a plain-text email. Found by reading one that had actually been
    sent, not by a test — so here is the test.
    """

    def setUp(self):
        self.client.force_login(make_receptionist())
        self.client.post(reverse("reception_add_doctor"), _form())
        self.message = mail.outbox[0]

    def test_no_html_entities_reach_the_reader(self):
        for entity in ("&amp;", "&#x27;", "&quot;", "&lt;", "&gt;", "&#39;"):
            self.assertNotIn(entity, self.message.body, msg=entity)

    def test_the_clinic_name_is_written_as_it_is_spelt(self):
        self.assertIn(settings.CLINIC.CLINIC_NAME, self.message.body)

    def test_the_subject_is_clean_too(self):
        self.assertNotIn("&amp;", self.message.subject)
