# Generated by Django 5.2.16 on 2026-07-30 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "advice",
                    models.TextField(
                        blank=True, help_text="Diet, activity and general advice."
                    ),
                ),
                (
                    "investigations_advised",
                    models.TextField(
                        blank=True, help_text="Tests to be done before the next visit."
                    ),
                ),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_notes", models.CharField(blank=True, max_length=300)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("printed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="patients.patient",
                    ),
                ),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription",
                        to="appointments.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", models.CharField(max_length=200)),
                (
                    "strength",
                    models.CharField(
                        blank=True, help_text="e.g. 50 mcg, 500 mg", max_length=50
                    ),
                ),
                (
                    "dosage",
                    models.CharField(
                        blank=True, help_text="e.g. 1 tablet", max_length=100
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Once daily before breakfast",
                        max_length=100,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text="e.g. 3 months", max_length=100
                    ),
                ),
                ("instructions", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pharmacy.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["patient", "-created_at"], name="pharmacy_pr_patient_e5426f_idx"
            ),
        ),
    ]
