# Generated by Django 5.2.16 on 2026-08-07 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_daysignoff"),
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="follow_up_date",
        ),
        migrations.AddField(
            model_name="prescription",
            name="follow_up_number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="follow_up_unit",
            field=models.CharField(
                blank=True,
                choices=[("MONTH", "Month(s)"), ("YEAR", "Year(s)")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="visit",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription",
                to="appointments.visit",
            ),
        ),
    ]
