# Generated by Django 5.2.16 on 2026-08-31 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0002_remove_prescription_follow_up_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="scanned_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="prescriptions/scans/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "pdf"]
                    )
                ],
            ),
        ),
    ]
