# Generated by Django 5.2.16 on 2026-08-04 16:28

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


#: The list a clinic starts with. Reception adds to it from the form, so this
#: is a starting point rather than a fixed set — but it wants to be broad
#: enough that the common cases are already there and nobody types
#: "Cardiology" for the first time on a Tuesday morning.
#:
#: Endocrinology sits first because this is an endocrine clinic.
STANDARD_SPECIALISATIONS = [
    "Endocrinology",
    "Paediatric Endocrinology",
    "Diabetology",
    "General Medicine",
    "Paediatrics",
    "Cardiology",
    "Dermatology",
    "ENT",
    "Gastroenterology",
    "General Surgery",
    "Gynaecology & Obstetrics",
    "Nephrology",
    "Neurology",
    "Oncology",
    "Ophthalmology",
    "Orthopaedics",
    "Psychiatry",
    "Pulmonology",
    "Radiology",
    "Rheumatology",
    "Urology",
]


def seed_specialisations(apps, schema_editor):
    Specialisation = apps.get_model("accounts", "Specialisation")
    for name in STANDARD_SPECIALISATIONS:
        Specialisation.objects.get_or_create(name=name)


def drop_seeded(apps, schema_editor):
    """
    Reverse: remove only the ones this migration put there.

    Anything reception added afterwards is theirs and stays, and a
    specialisation a doctor is actually on is protected by the foreign key.
    """
    Specialisation = apps.get_model("accounts", "Specialisation")
    Specialisation.objects.filter(
        name__in=STANDARD_SPECIALISATIONS, doctors__isnull=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_doctorprofile_activated_at_doctorprofile_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Unticked, this stays on existing doctors but is not offered for new ones.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specialisations_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="specialisation",
            field=models.ForeignKey(
                blank=True,
                help_text="What this doctor specialises in. Drives the calendar filter.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="doctors",
                to="accounts.specialisation",
            ),
        ),
        migrations.AddConstraint(
            model_name="specialisation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="specialisation_name_unique_ci",
            ),
        ),
        migrations.RunPython(seed_specialisations, drop_seeded),
        # Removed last, and deliberately without translating the old values.
        #
        # KAN-21 shipped Adult / Paediatric / Adult & paediatric. Those are a
        # division of the patient list, not specialisations, so there is no
        # correct mapping from one to the other — and guessing would write a
        # clinical label onto a doctor that nobody at the clinic chose. Existing
        # doctors show "Not set" until somebody picks, which takes a moment and
        # is certainly right.
        migrations.RemoveField(
            model_name="doctorprofile",
            name="category",
        ),
    ]
