# Generated by Django 5.2.16 on 2026-08-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_specialisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Shown on the public website. Leave a blank line between paragraphs.",
            ),
        ),
    ]
