# Generated by Django 5.2.16 on 2026-08-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_doctorprofile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="areas_of_focus",
            field=models.TextField(
                blank=True,
                help_text="Shown on the public website as a bullet list. One per line.",
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="further_training",
            field=models.TextField(
                blank=True,
                help_text="Shown on the public website as a bullet list, e.g. 'Clinical Observership — Royal Children's Hospital, Melbourne'. One per line. Leave blank if none.",
            ),
        ),
    ]
