# Generated by Django 5.2.16 on 2026-08-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_doctorprofile_areas_of_focus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Shown on the public website. Portrait orientation, face in the upper third, works best.",
                null=True,
                upload_to="doctor_photos/",
            ),
        ),
    ]
