# Generated by Django 5.2.16 on 2026-07-30 10:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measured_on",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "head_circumference_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Clinically meaningful under about 3 years.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "waist_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "puberty_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Stage 1 (prepubertal)"),
                            ("2", "Stage 2"),
                            ("3", "Stage 3"),
                            ("4", "Stage 4"),
                            ("5", "Stage 5 (adult)"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "mother_height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "father_height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="patients.patient",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_measurements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="measurements",
                        to="appointments.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["-measured_on"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-measured_on"],
                        name="growth_meas_patient_48ede4_idx",
                    )
                ],
            },
        ),
    ]
