# Generated by Django 5.2.16 on 2026-08-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="bone_age_years",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="From an X-ray reading, e.g. 8.3 for 8 years 3 months.",
                max_digits=4,
                null=True,
            ),
        ),
    ]
