# Generated by Django 5.2.16 on 2026-07-30 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=150)),
                ("user_role", models.CharField(blank=True, max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("VIEW", "Viewed"),
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                            ("PRINT", "Printed"),
                            ("LOGIN", "Logged in"),
                            ("LOGIN_FAILED", "Failed login"),
                            ("LOGOUT", "Logged out"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_type", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=50)),
                (
                    "patient_id_ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        verbose_name="patient ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("path", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "access log entry",
                "verbose_name_plural": "access log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient_id_ref", "-created_at"],
                        name="audit_acces_patient_1e91e1_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="audit_acces_user_id_dd408e_idx",
                    ),
                ],
            },
        ),
    ]
