# Generated by Django 5.2.16 on 2026-07-30 10:33

import appointments.models
import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Must come first: the no-double-booking exclusion constraint below
        # mixes an equality test on `doctor` with an overlap test on a time
        # range, and GiST cannot index a plain bigint without this extension.
        BtreeGistExtension(),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Booked"),
                            ("CONFIRMED", "Confirmed"),
                            ("ARRIVED", "Arrived"),
                            ("IN_CABIN", "In cabin"),
                            ("CONSULTED", "Consulted"),
                            ("BILLED", "Billed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No show"),
                        ],
                        db_index=True,
                        default="BOOKED",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Why the patient is coming in.",
                        max_length=300,
                    ),
                ),
                ("is_follow_up", models.BooleanField(default=False)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("entered_cabin_at", models.DateTimeField(blank=True, null=True)),
                ("consulted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Receptionist who took the booking; empty if the patient booked online.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visits_booked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "DOCTOR"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits_as_doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="VisitStatusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Booked"),
                            ("CONFIRMED", "Confirmed"),
                            ("ARRIVED", "Arrived"),
                            ("IN_CABIN", "In cabin"),
                            ("CONSULTED", "Consulted"),
                            ("BILLED", "Billed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No show"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Booked"),
                            ("CONFIRMED", "Confirmed"),
                            ("ARRIVED", "Arrived"),
                            ("IN_CABIN", "In cabin"),
                            ("CONSULTED", "Consulted"),
                            ("BILLED", "Billed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No show"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_events",
                        to="appointments.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "visit status event",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["scheduled_start", "status"],
                name="appointment_schedul_9e4d62_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["patient", "-scheduled_start"],
                name="appointment_patient_079ab0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="visit",
            constraint=models.CheckConstraint(
                condition=models.Q(("scheduled_end__gt", models.F("scheduled_start"))),
                name="visit_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="visit",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(
                    ("status__in", ["CANCELLED", "NO_SHOW", "COMPLETED"]), _negated=True
                ),
                expressions=[
                    (
                        appointments.models.TsTzRange(
                            "scheduled_start",
                            "scheduled_end",
                            django.contrib.postgres.fields.ranges.RangeBoundary(),
                        ),
                        "&&",
                    ),
                    ("doctor", "="),
                ],
                name="visit_no_double_booking",
            ),
        ),
    ]
