# Generated by Django 5.2.16 on 2026-08-04 16:40

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_clinicholiday_doctorleave_doctorschedule_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cabin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Unticked, this stays on existing entries but is not offered for new ones.",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cabins_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="doctorschedule",
            name="cabin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="weekly_sittings",
                to="appointments.cabin",
            ),
        ),
        migrations.AddField(
            model_name="scheduleoverride",
            name="cabin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="one_off_sittings",
                to="appointments.cabin",
            ),
        ),
        migrations.AddConstraint(
            model_name="cabin",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="cabin_name_unique_ci",
            ),
        ),
    ]
