# Generated by Django 5.2.16 on 2026-08-06 11:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_cabin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DaySignOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("sent_to", models.CharField(blank=True, max_length=320)),
                ("billed_count", models.PositiveIntegerField(default=0)),
                ("cancelled_count", models.PositiveIntegerField(default=0)),
                ("no_show_count", models.PositiveIntegerField(default=0)),
                (
                    "collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("delivery_error", models.CharField(blank=True, max_length=300)),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="day_sign_offs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "day sign-off",
                "ordering": ["-date"],
            },
        ),
    ]
