# Generated by Django 5.2.16 on 2026-08-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_daysignoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="is_walk_in",
            field=models.BooleanField(default=False),
        ),
    ]
