# Generated by Django 5.2.16 on 2026-08-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0010_remove_doctorleave"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="is_direct",
            field=models.BooleanField(default=False),
        ),
    ]
