# Generated by Django 5.2.16 on 2026-07-30 10:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Clinic-wide unique identifier. Generated on registration; never changes.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit Indian mobile number.",
                                regex="^(\\+91[\\-\\s]?)?[0]?[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit Indian mobile number.",
                                regex="^(\\+91[\\-\\s]?)?[0]?[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("guardian_name", models.CharField(blank=True, max_length=200)),
                (
                    "guardian_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit Indian mobile number.",
                                regex="^(\\+91[\\-\\s]?)?[0]?[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("guardian_relation", models.CharField(blank=True, max_length=50)),
                ("referred_by", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "registered_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="PatientHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("presenting_complaints", models.TextField(blank=True)),
                ("past_medical_history", models.TextField(blank=True)),
                (
                    "family_history",
                    models.TextField(
                        blank=True,
                        help_text="Especially diabetes, thyroid and endocrine disorders.",
                    ),
                ),
                (
                    "birth_history",
                    models.TextField(
                        blank=True,
                        help_text="Paediatric: birth weight, gestation, delivery, milestones.",
                    ),
                ),
                ("allergies", models.TextField(blank=True)),
                ("current_medications", models.TextField(blank=True)),
                ("surgical_history", models.TextField(blank=True)),
                ("lifestyle_notes", models.TextField(blank=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "patient history",
                "verbose_name_plural": "patient histories",
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="patients_pa_last_na_1b32a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["phone"], name="patients_pa_phone_fc49bb_idx"),
        ),
    ]
